version: '3.8'

services:
  doc2:
    container_name: doc1
    build: .
    ports:
      - "127.0.0.1:3001:3000"  # Expose port 5000 on the specific IP address
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
