version: '3.8'

services:
  doc2:
    container_name: doc2
    build: .
    ports:
      - "127.0.0.1:5001:5000"  # Expose port 5000 on the specific IP address
    volumes:
      - ./input:/input
      - ./output:/output
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
